apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: test-work
  namespace: default
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-nginx
        namespace: default
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: test-nginx
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: test-nginx
          spec:
            containers:
            - image: nginx:1.14.2
              name: nginx
              ports:
              - containerPort: 80
              resources: {}
  workloadConfig:
    manifestConfigs:
      - resourceIdentifier:
          group: apps
          kind: Deployment
          version: v1
        statusSyncRules:
        - type: CommonFields
        - type: JSONPaths
          jsonPaths:
          - name: isAvailable
            path: '.status.conditions[?(@.type=="Available")].status'
