name: CI Workflow
on:
  # Run this workflow every time a new commit pushed to upstream/fork repository.
  # Run workflow on fork repository will help contributors find and resolve issues before sending a PR.
  pull_request:
defaults:
  run:
    working-directory: go/src/sigs.k8s.io/work-api

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # the version of golangci-lint.
          version: v1.45.2

          # show only new issues if it's a pull request.
          only-new-issues: false
          args: --timeout 3m0s
